In [38]:
import pandas as pd
df = pd.read_csv("films.csv")

df.tail(30)

,film_id,realisateur_id,rang,titre,titre_vo,realisateur,genre,annee,pays,entrees,salles,moy_salle,part_marche,affiche,moyenne_fr_realisateur,sortie,distributeur,classification,acteurs,moyenne_fr_acteurs
0,701,147.0,7,La Revanche des Sith,Revenge of the Sith,George Lucas,Fantasy,2005,f23,3303005,938,3521,46 %,cinema/images/posters/revengesith.jpg,2872369.0,18/05/2005,20th Century Fox,Tous publics,"[{'id': '123', 'name': 'Ewan McGregor', 'role'...",1094653
1,13345,575.0,3,Star Wars: Le Réveil de la Force,Star Wars: The Force Awakens,J.J. Abrams,Fantasy,2015,f23,3801235,1093,3478,36 %,cinema/images/posters/13345-20230308062242.jpg,3591013.0,16/12/2015,Walt Disney Pictures,Tous publics,"[{'id': '157', 'name': 'Harrison Ford', 'role'...",1476045
2,17528,505.0,8,Le Roi Lion (2019),The Lion King (2019),Jon Favreau,Aventure - Action,2019,f23,3252896,680,4784,32 %,cinema/images/posters/17528-20190713012150-0.jpg,2453685.0,17/07/2019,Walt Disney Pictures,Tous publics,"[{'id': '182', 'name': 'Jamel Debbouze', 'role...",1278950
3,2398,438.0,5,Taxi 2,Taxi 2,Gérard Krawczyk,Comédie,2000,f25,3478850,831,4186,34 %,cinema/images/posters/taxi2.jpg,2573794.0,29/03/2000,ARP Selection,Tous publics,"[{'id': '131', 'name': 'Frédéric Diefenthal', ...",1440504
4,10845,333.0,9,Les Aventures de Tintin : Le secret de la Licorne,The Adventures of Tintin: Secret of the Unicorn,Steven Spielberg,Aventure - Action,2011,f23,3158313,850,3716,59 %,cinema/images/posters/10845-20110827120831.jpg,2541723.0,26/10/2011,Sony Pictures,Tous publics,"[{'id': '104', 'name': 'Daniel Craig', 'role':...",1177386
5,2077,432.0,16,La Vérité si je mens! 2,La Vérité Si Je Mens! 2 (Would I Lie to You? 2),Thomas Gilou,Comédie,2001,f25,2830489,827,3423,36 %,cinema/images/posters/veritesijemens2.jpg,2448000.0,07/02/2001,Warner Bros.,Tous publics,"[{'id': '430', 'name': 'Richard Anconina', 'ro...",1468767
6,10042,947.0,1,Bienvenue chez les Ch'tis,Bienvenue chez les Ch'tis,Dany Boon,Comédie,2008,f25,4378720,793,5522,21 %,cinema/images/posters/np_10042.jpg,6579581.0,27/02/2008,Pathé,Tous publics,"[{'id': '534', 'name': 'Dany Boon', 'role': 'R...",1901941
7,320,282.0,2,Les Bronzés 3: Amis pour la vie,Les Bronzés 3: Amis pour la vie,Patrice Leconte,Comédie,2006,f25,3906694,950,4112,38 %,cinema/images/posters/bronzes3.jpg,1196164.0,01/02/2006,Warner Bros.,Tous publics,"[{'id': '242', 'name': 'Michel Blanc', 'role':...",1234588
8,18826,174.0,17,Avatar : la voie de l'eau,Avatar: The Way of Water,James Cameron,Science Fiction,2022,f23,2739848,762,3596,20 %,cinema/images/posters/18826-20230308061935.jpg,4463414.0,14/12/2022,Walt Disney Pictures,Tous publics,"[{'id': '613', 'name': 'Sam Worthington', 'rol...",1567178
9,12,885.0,13,Harry Potter et le Prince de sang-mêlé,Harry Potter and the Half-Blood Prince,David Yates,Fantasy,2009,f23,2882397,949,3037,48 %,cinema/images/posters/12-20140126072615-2.jpg,4621211.0,15/07/2009,Warner Bros.,Tous publics,"[{'id': '835', 'name': 'Daniel Radcliffe', 'ro...",2642756
10,21065,1016.0,14,Spider-Man: No Way Home,Spider-Man: No Way Home,Jon Watts,Comicbook,2021,f23,2867515,882,3251,39 %,cinema/images/posters/21065-20211111084515-0.jpg,3231363.0,15/12/2021,Sony Pictures,Tous publics,"[{'id': '843', 'name': 'Benedict Cumberbatch',...",1457528
11,1400,281.0,15,Le Seigneur des anneaux: Le Retour du roi,The Lord of the Rings: The Return of the King,Peter Jackson,Fantasy,2003,f23,2852784,993,2873,39 %,cinema/images/posters/returnking.jpg,2102849.0,17/12/2003,Metropolitan,Tous publics,"[{'id': '276', 'name': 'Orlando Bloom', 'role'...",1500365
12,3,NaN,12,Asterix aux Jeux Olympiques,NaN,NaN,Comédie,2008,f25,3007811,1078,2790,44 %,cinema/images/posters/np_3.jpg,NaN,30/01/2008,Pathé,Tous publics,"[{'id': '142', 'name': 'Gérard Depardieu', 'ro...",1287646
13,700,445.0,11,Harry Potter et la coupe de feu,Harry Potter and the Goblet of Fire,Mike Newell,Fantasy,2005,f23,3088796,950,3251,40 %,cinema/images/posters/harrypotter4.jpg,1706499.0,30/11/2005,Warner Bros.,NaN,"[{'id': '835', 'name': 'Daniel Radcliffe', 'ro...",2287712
14,1742,89.0,18,Harry Potter et la chambre des secrets,Harry Potter and the Chamber of Secrets,Chris Columbus,Fantasy,2002,f23,2728766,1007,2710,30 %,cinema/images/posters/harrypotter2.jpg,2130394.0,04/12/2002,Warner Bros.,NaN,"[{'id': '835', 'name': 'Daniel Radcliffe', 'ro...",2660536
15,3039,201.0,22,Les Visiteurs II - Les Couloirs du temps,Les Visiteurs II - Les Couloirs du temps,Jean-Marie Poiré,Comédie,1998,f25,2655916,600,4427,33 %,cinema/images/posters/visiteurs2.jpg,3107128.0,11/02/1998,GBVI,Tous publics,"[{'id': '210', 'name': 'Jean Reno', 'role': 'R...",1668970
16,9975,174.0,23,Avatar,Avatar,James Cameron,Science Fiction,2009,f23,2648596,726,3648,18 %,cinema/images/posters/9975-20230308064048.jpg,4463414.0,16/12/2009,20th Century Fox,Tous publics,"[{'id': '613', 'name': 'Sam Worthington', 'rol...",1586045
17,2704,102.0,19,Astérix et Obélix contre César,Astérix et Obélix contre César,Claude Zidi,Comédie,1999,f25,2718443,780,3485,30 %,cinema/images/posters/asterix1.jpg,3204355.0,03/02/1999,Pathé,Tous publics,"[{'id': '142', 'name': 'Gérard Depardieu', 'ro...",1591778
18,10193,885.0,10,Harry Potter et les reliques de la mort - part...,Harry Potter and the Deathly Hallows: Part II,David Yates,Fantasy,2011,f23,3129485,812,3854,48 %,cinema/images/posters/10193-20110702040722.jpg,4621211.0,13/07/2011,Warner Bros.,Tous publics,"[{'id': '300', 'name': 'Ralph Fiennes', 'role'...",2182009
19,321,154.0,21,"Pirates des Caraïbes, le secret du coffre maudit",Pirates of the Caribbean: Dead Man's Chest,Gore Verbinski,Aventure - Action,2006,f23,2708112,750,3611,41 %,cinema/images/posters/piratescaraibes2.jpg,1987433.0,02/08/2006,Walt Disney Pictures,Tous publics,"[{'id': '185', 'name': 'Johnny Depp', 'role': ...",1533156
20,28,154.0,20,"Pirates des Caraïbes, jusqu'au bout du monde",Pirates of the Caribbean : At World's End,Gore Verbinski,Aventure - Action,2007,f23,2709377,783,3460,47 %,cinema/images/posters/p_5109.jpg,1987433.0,23/05/2007,Walt Disney Pictures,Tous publics,"[{'id': '185', 'name': 'Johnny Depp', 'role': ...",1383966
21,1741,777.0,4,Astérix et Obélix: Mission Cléopatre,Astérix et Obélix: Mission Cléopatre,Alain Chabat,Comédie,2002,f25,3685097,945,3900,25 %,cinema/images/posters/asterixcleopatre.jpg,4478003.0,30/01/2002,Pathé,Tous publics,"[{'id': '83', 'name': 'Christian Clavier', 'ro...",1371681
22,15113,962.0,27,Star Wars: Les derniers Jedi,Star Wars: The Last Jedi,Rian Johnson,Fantasy,2017,f23,2510462,1027,2444,35 %,cinema/images/posters/15113-20170415020115-0.jpg,1829232.0,13/12/2017,Walt Disney Pictures,Tous publics,"[{'id': '971', 'name': 'Adam Driver', 'role': ...",1008082
23,11191,947.0,24,Rien à déclarer,Rien à déclarer,Dany Boon,Comédie,2011,f25,2587056,1036,2497,32 %,cinema/images/posters/11191-20101022071008.jpg,6579581.0,02/02/2011,Pathé,Tous publics,"[{'id': '534', 'name': 'Dany Boon', 'role': 'R...",1238033
24,1045,441.0,28,Harry Potter et le prisonnier d'Azkaban,Harry Potter and the Prisoner of Azkaban,Alfonso Cuaron,Fantasy,2004,f23,2503699,907,2760,35 %,cinema/images/posters/harrypotter3.jpg,2011476.0,02/06/2004,Warner Bros.,NaN,"[{'id': '835', 'name': 'Daniel Radcliffe', 'ro...",2431061
25,17666,947.0,30,La Ch’tite famille,La Ch’tite famille,Dany Boon,Comédie,2018,f25,2429906,843,2882,43 %,cinema/images/posters/17666-20171221080308-0.jpg,6579581.0,28/02/2018,Pathé,Tous publics,"[{'id': '534', 'name': 'Dany Boon', 'role': 'R...",1299124
26,9839,885.0,26,Harry Potter et les reliques de la mort - part...,Harry Potter and the Deathly Hallows: Part I,David Yates,Fantasy,2010,f23,2537450,971,2613,42 %,cinema/images/posters/9839-20101103081138.jpg,4621211.0,24/11/2010,Warner Bros.,Tous publics,"[{'id': '835', 'name': 'Daniel Radcliffe', 'ro...",2282348
27,133,885.0,29,Harry Potter et l'Ordre du Phénix,Harry Potter and the Order of the Phoenix,David Yates,Fantasy,2007,f23,2486291,950,2617,40 %,cinema/images/posters/p_45.jpg,4621211.0,11/07/2007,Warner Bros.,Tous publics,"[{'id': '710', 'name': 'Robert Pattinson', 'ro...",2107093
28,15189,967.0,6,Avengers: Endgame,Avengers: Endgame,- Russo (brothers),Comicbook,2019,f23,3426471,633,5413,49 %,cinema/images/posters/15189-20190317125524-0.jpg,2851359.0,24/04/2019,Walt Disney Pictures,Tous publics,"[{'id': '828', 'name': 'Chris Evans', 'role': ...",1415542
29,15188,967.0,25,Avengers: Infinity War,Avengers: Infinity War,- Russo (brothers),Comicbook,2018,f23,2565953,843,3044,50 %,cinema/images/posters/15188-20230308071344.jpg,2851359.0,25/04/2018,Walt Disney Pictures,Tous publics,"[{'id': '828', 'name': 'Chris Evans', 'role': ...",1403501

In [41]:
import pandas as pd
casting= pd.read_csv("casting_detail.csv")

casting.tail(30)

,film_id,person_id,nom_personne,role,personnage,photo_path,nb_films,cumul_FR,moyenne_FR,cumul_US
0,2,892,Kristen Wiig,Acteurs et actrices,- Maman castor,cinema/images/acteurs/892.jpg,32,6940184,433762,1331658899
1,2,594,Elie Semoun,Acteurs et actrices,- Sid (voix française),cinema/images/acteurs/594.jpg,42,48749252,1189006,75585093
2,2,658,- Queen Latifah,Acteurs et actrices,- Ellie,cinema/images/acteurs/658-20120625100651.jpg,32,7251268,315273,1603487678
3,1,237,Liam Neeson,Acteurs et actrices,- Aslan,cinema/images/acteurs/237-20120129110135.jpg,85,53204694,806132,3486335149
4,1,26,Michael Apted,Realisateur(s),NaN,cinema/images/acteurs/apted.jpg,30,11115320,793951,580724697
5,2,349,Vincent Cassel,Acteurs et actrices,- Diego (voix française),cinema/images/acteurs/vcassel.jpg,66,54561090,940708,659194961
6,1,608,Simon Pegg,Acteurs et actrices,- Reepicheep,cinema/images/acteurs/608.jpg,29,16848022,842401,1625997872
7,2,146,Gérard Lanvin,Acteurs et actrices,- Manny (voix française),cinema/images/acteurs/146-20151228043224.jpg,60,64082712,1086148,1874709
8,3,142,Gérard Depardieu,Acteurs et actrices,- Obélix,cinema/images/acteurs/gdepardieu.jpg,185,226636837,1310040,448683864
9,3,756,René Goscinny,Acteurs et actrices,NaN,cinema/images/acteurs/nophoto.jpg,27,76271184,2824859,6031201
10,3,182,Jamel Debbouze,Acteurs et actrices,- Numérobis,cinema/images/acteurs/182-20150405112120.jpg,25,55173457,2206938,37555994
11,3,541,Franck Dubosc,Acteurs et actrices,- Assurancetourix,cinema/images/acteurs/541-20120409010428.jpg,48,54297453,1206610,856
12,3,189,José Garcia,Acteurs et actrices,- Couverdepus,cinema/images/acteurs/189-20120130100116.jpg,64,68664345,1089910,118803316
13,3,5,Alain Delon,Acteurs et actrices,- Jules César,cinema/images/acteurs/adelon.jpg,84,136659364,1646498,47415688
14,3,57,Benoît Poelvoorde,Acteurs et actrices,- Brutus,cinema/images/acteurs/57-20120604090642.jpg,65,53755515,839930,6501812
15,3,91,Clovis Cornillac,Acteurs et actrices,- Astérix,cinema/images/acteurs/91-20120310050326.jpg,69,53607695,812238,17859463